# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.1.dev202+g63b9f61.d20221212"
__version_tuple__ = version_tuple = (0, 1, "dev202", "g63b9f61.d20221212")
