# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.1.dev298+g4fe55d7.d20230309"
__version_tuple__ = version_tuple = (0, 1, "dev298", "g4fe55d7.d20230309")
