output_folder: s3://dea-public-data-dev/projects/burn_cube/burn-cube-s2/4gm-7bands

input_products:
  platform: s2
  geomed: ga_s2a_debug_gm_4fyear_3
  wofs_summary: ga_ls_wo_fq_cyear_3
  ard_product_names:
    - ga_s2am_ard_3
  input_ard_bands:
    - nbart_blue
    - nbart_green
    - nbart_red
    - nbart_nir_2
    - nbart_swir_2
    - nbart_swir_3
  input_gm_bands:
    - nbart_blue
    - nbart_green
    - nbart_red
    - nbart_nir_2
    - nbart_swir_2
    - nbart_swir_3

task_table: 10-year-historical-processing-4year-geomad.csv
