output_folder: s3://dea-public-data-dev/projects/burn_cube/burn-cube-s2-ab/4gm-7bands

input_products:
  platform: s2
  geomed_name: ga_s2ab_debug_gm_4fyear_3
  wofs_summary_name: ga_ls_wo_fq_cyear_3
  ard_names:
    - ga_s2am_ard_3
    - ga_s2bm_ard_3
  input_ard_bands:
    - nbart_blue
    - nbart_green
    - nbart_red
    - nbart_nir_2
    - nbart_swir_2
    - nbart_swir_3
  input_gm_bands:
    - nbart_blue
    - nbart_green
    - nbart_red
    - nbart_nir_2
    - nbart_swir_2
    - nbart_swir_3

product:
  name: bc_s2ab_fy_debug
  short_name: bc_s2ab_fy_debug
  version: 3.0.0
  product_family: burncube
  bands:
    - wofssevere
    - wofsseverity
    - wofsmoderate
    - severe
    - severity
    - moderate
    - count

task_table: 10-year-historical-processing-4year-geomad.csv
